services:
  - type: web
    name: sistema-gestion-ventas
    plan: free
    region: oregon
    env: docker
    dockerfilePath: ./Dockerfile
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: sistema-gestion-ventas-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sistema-gestion-ventas-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sistema-gestion-ventas-db
          property: password

databases:
  - name: sistema-gestion-ventas-db
    databaseName: sistema_ventas
    plan: free
    region: oregon